/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Conexion.Conexion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class panelInventario extends javax.swing.JPanel {

    /**
     * Creates new form panelInventario
     */
    public panelInventario() {
        initComponents();
        setVisible(true);
        mostrarpanelMedicamento();

        btnMed.setBackground(new ColorUIResource(51, 204, 255));
        btnMed.setForeground(Color.BLACK);

        btnFabricante.setBackground(Color.darkGray);
        btnFabricante.setForeground(Color.WHITE);

        btnFarmtico.setBackground(Color.darkGray);
        btnFarmtico.setForeground(Color.WHITE);

        btnFarmacia.setBackground(Color.darkGray);
        btnFarmacia.setForeground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        panelMenuAgregar = new javax.swing.JPanel();
        btnMed = new javax.swing.JButton();
        btnFabricante = new javax.swing.JButton();
        btnFarmacia = new javax.swing.JButton();
        btnFarmtico = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        content.setMinimumSize(new java.awt.Dimension(800, 600));
        content.setPreferredSize(new java.awt.Dimension(800, 600));
        content.setLayout(new java.awt.BorderLayout());
        add(content, java.awt.BorderLayout.CENTER);

        panelMenuAgregar.setMinimumSize(new java.awt.Dimension(337, 50));
        panelMenuAgregar.setPreferredSize(new java.awt.Dimension(800, 50));
        panelMenuAgregar.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        btnMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnMed.setText("Medicamento");
        btnMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedActionPerformed(evt);
            }
        });
        panelMenuAgregar.add(btnMed);

        btnFabricante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnFabricante.setText("Fabricante");
        btnFabricante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFabricanteActionPerformed(evt);
            }
        });
        panelMenuAgregar.add(btnFabricante);

        btnFarmacia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnFarmacia.setText("Farmacia");
        btnFarmacia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmaciaActionPerformed(evt);
            }
        });
        panelMenuAgregar.add(btnFarmacia);

        btnFarmtico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnFarmtico.setText("Farmaceutico");
        btnFarmtico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFarmtico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmticoActionPerformed(evt);
            }
        });
        panelMenuAgregar.add(btnFarmtico);

        add(panelMenuAgregar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedActionPerformed
        // TODO add your handling code here:
        mostrarpanelMedicamento();
        BotonSeleccionado(evt);
    }//GEN-LAST:event_btnMedActionPerformed

    private void btnFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFabricanteActionPerformed
        // TODO add your handling code here:
        mostrarpanelFabri();
        BotonSeleccionado(evt);
    }//GEN-LAST:event_btnFabricanteActionPerformed

    private void btnFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmaciaActionPerformed
        mostrarpanelFarmacia();
        BotonSeleccionado(evt);
    }//GEN-LAST:event_btnFarmaciaActionPerformed

    private void btnFarmticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmticoActionPerformed
        // TODO add your handling code here:
        mostrarpanelFarmaceutico();
        BotonSeleccionado(evt);
    }//GEN-LAST:event_btnFarmticoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFabricante;
    private javax.swing.JButton btnFarmacia;
    private javax.swing.JButton btnFarmtico;
    private javax.swing.JButton btnMed;
    private javax.swing.JPanel content;
    private javax.swing.JPanel panelMenuAgregar;
    // End of variables declaration//GEN-END:variables

    private void mostrarpanelMedicamento() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        content.removeAll();
        content.revalidate();
        panelMed med = new panelMed();
        content.add(med);
    }

    private void mostrarpanelFabri() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        content.removeAll();
        content.revalidate();
        panelFabricante droga = new panelFabricante();
        content.add(droga);
    }

    private void mostrarpanelFarmacia() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        content.removeAll();
        content.revalidate();
        panelFarmacia farm = new panelFarmacia();
        content.add(farm);
    }

    private void mostrarpanelFarmaceutico() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        content.removeAll();
        content.revalidate();
        panelFarmaceutico far = new panelFarmaceutico();
        content.add(far);
    }

    private void BotonSeleccionado(ActionEvent evt) {
        switch (evt.getActionCommand()) {
            case "Medicamento": {

                btnMed.setBackground(new ColorUIResource(51, 204, 255));
                btnMed.setForeground(Color.BLACK);

                btnFabricante.setBackground(Color.darkGray);
                btnFabricante.setForeground(Color.WHITE);

                btnFarmtico.setBackground(Color.darkGray);
                btnFarmtico.setForeground(Color.WHITE);

                btnFarmacia.setBackground(Color.darkGray);
                btnFarmacia.setForeground(Color.WHITE);
                break;
            }
            case "Fabricante": {

                btnFabricante.setBackground(new ColorUIResource(51, 204, 255));
                btnFabricante.setForeground(Color.BLACK);

                btnMed.setBackground(Color.darkGray);
                btnMed.setForeground(Color.WHITE);

                btnFarmacia.setBackground(Color.darkGray);
                btnFarmacia.setForeground(Color.WHITE);

                btnFarmtico.setBackground(Color.darkGray);
                btnFarmtico.setForeground(Color.WHITE);

                break;
            }
            case "Farmaceutico": {
                System.out.println("Venta: " + evt.getActionCommand());

                btnFarmtico.setBackground(new ColorUIResource(51, 204, 255));
                btnFarmtico.setForeground(Color.BLACK);

                btnMed.setBackground(Color.darkGray);
                btnMed.setForeground(Color.WHITE);

                btnFarmacia.setBackground(Color.darkGray);
                btnFarmacia.setForeground(Color.WHITE);

                btnFabricante.setBackground(Color.darkGray);
                btnFabricante.setForeground(Color.WHITE);

                break;
            }
            case "Farmacia": {
                System.out.println("Compra: " + evt.getActionCommand());

                btnFarmacia.setBackground(new ColorUIResource(51, 204, 255));
                btnFarmacia.setForeground(Color.BLACK);

                btnMed.setBackground(Color.darkGray);
                btnMed.setForeground(Color.WHITE);

                btnFabricante.setBackground(Color.darkGray);
                btnFabricante.setForeground(Color.WHITE);

                btnFarmtico.setBackground(Color.darkGray);
                btnFarmtico.setForeground(Color.WHITE);

                break;
            }

            default: {
                btnFarmacia.setBackground(Color.darkGray);
                btnFarmacia.setForeground(Color.WHITE);

                btnMed.setBackground(Color.darkGray);
                btnMed.setForeground(Color.WHITE);

                btnFabricante.setBackground(Color.darkGray);
                btnFabricante.setForeground(Color.WHITE);

                btnFarmtico.setBackground(Color.darkGray);
                btnFarmtico.setForeground(Color.WHITE);

                break;
            }
        }

    }

}
